
export const INITIALIZE_CLIENT = 'INITIALIZE_CLIENT';

export const SET_STATUS = 'SET_STATUS';
export const IMAGES_READY = 'IMAGES_READY';
export const SET_COLOR_THEME = 'SET_COLOR_THEME';

export const TOGGLE_FUTURE_MODE = 'TOGGLE_FUTURE_MODE';
export const TOGGLE_FORECAST_TIMEZONE_MODE = 'TOGGLE_FORECAST_TIMEZONE_MODE';
export const TOGGLE_GRADIENT_MODE = 'TOGGLE_GRADIENT_MODE';
export const TOGGLE_SECOND_HAND_MODE = 'TOGGLE_SECOND_HAND_MODE';
export const SET_UNIT_MODE = 'SET_UNIT_MODE';
export const SET_DATA_MODE = 'SET_DATA_MODE';
export const SET_CLOCK_SIZE = 'SET_CLOCK_SIZE';

export const FETCH_WEATHER_DATA_SUCCEEDED = 'FETCH_WEATHER_DATA_SUCCEEDED';
export const FETCH_WEATHER_DATA_FAILED = 'FETCH_WEATHER_DATA_FAILED';
export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const RESET_WEATHER_DATA = 'RESET_WEATHER_DATA';
export const FETCH_WEATHER_DATA_STARTED = 'FETCH_WEATHER_DATA_STARTED';

export const OPEN_ABOUT_DIALOG = 'OPEN_ABOUT_DIALOG';
export const CLOSE_ABOUT_DIALOG = 'CLOSE_ABOUT_DIALOG';
export const OPEN_SETTINGS_DIALOG = 'OPEN_SETTINGS_DIALOG';
export const CLOSE_SETTINGS_DIALOG = 'CLOSE_SETTINGS_DIALOG';
export const OPEN_NOTIFICATION_DIALOG = 'OPEN_NOTIFICATION_DIALOG';
export const CLOSE_NOTIFICATION_DIALOG = 'CLOSE_NOTIFICATION_DIALOG';
